// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9oI3RebdYrAM2wjlN3YPduz2x416t1E',
    appId: '1:255166792722:web:f579a23ae38d0318ea44cb',
    messagingSenderId: '255166792722',
    projectId: 'beach-ca761',
    authDomain: 'beach-ca761.firebaseapp.com',
    storageBucket: 'beach-ca761.appspot.com',
    measurementId: 'G-14EE4X50NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjS5wt1YigQLVQ7wYOqNQDXKmV21BVyc',
    appId: '1:255166792722:android:9c03655531b41e0eea44cb',
    messagingSenderId: '255166792722',
    projectId: 'beach-ca761',
    storageBucket: 'beach-ca761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRI8DoBvwdy2VJzdUrWiM4hNabpRKhR9c',
    appId: '1:255166792722:ios:341170af2aca85e4ea44cb',
    messagingSenderId: '255166792722',
    projectId: 'beach-ca761',
    storageBucket: 'beach-ca761.appspot.com',
    iosBundleId: 'com.example.beach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRI8DoBvwdy2VJzdUrWiM4hNabpRKhR9c',
    appId: '1:255166792722:ios:7d1f85b1055e4daaea44cb',
    messagingSenderId: '255166792722',
    projectId: 'beach-ca761',
    storageBucket: 'beach-ca761.appspot.com',
    iosBundleId: 'com.example.beach.RunnerTests',
  );
}
